# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e411c5885c72f22ed570156f0f0b6d6d7e8b2bf8457750fd6533f1d229572dadafd29842f6cb20fd60c9f1856eae1c4de8dfcf51d0d4e028fe75d5dce9d5370

test:
  secret_key_base: b7d673b1cf0533feec46184e6f351328cd73c979e33af66ad944da41b3ec9417da857a20671d15319d59afab374871316560b099c53598a87f0eb9000af0751f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
